### ISSUE TITLE
Most indicators do not work

### ISSUE THREAD

**Issue by cndreisbach** [ClojureBridge/global-growth#1]
I am not sure if this is by design -- like they should be implemented in class -- or not, but only a few of the indicators return any data.

**Comment by bridgethillyer** [comment]
Finding a subset of the indicators to retrieve for the initial list that will return data is a problem that still needs to be solved. Getting the full set of indicators doesn't make sense either, because there are way too many of them (8800?) For now, I changed which subset gets populated into the initial list so that you can more easily find data with them.
