### ISSUE TITLE
Typo in GitHub metadata for the ClojureBridge/global-growth Repo: Wold Bank API > World Bank API

### ISSUE THREAD

**Issue by ondine** [ClojureBridge/global-growth#17]

**Comment by k4y3ff** [comment]
...we should fix this. Who's the owner?

**Comment by davidchambers** [comment]
Good question. Are you an owner, @bridgethillyer?

**Comment by bridgethillyer** [comment]
The same rules apply here (and in drawing) as do in the main repo - expressed in the Contributing doc there. (Should copy that into both repos). I.e. group ownership by anyone in the curriculum group.

**Comment by k4y3ff** [comment]
Ah, sorry for being unclear. By "owner," I literally meant "Who has owner permissions on this repo?"

Everyone in the curriculum group has collaborator access, but a higher permission level is required to change the name/subtitle of repos. So, most people in the curriculum group would not be able to close an issue like this.

(Someone specifically asked me to close this issue at the SF workshop, which is why I asked who among us had the appropriate permissions.)

**Comment by bridgethillyer** [comment]
Ah! got it. The owners for all the ClojureBridge repos are:
@bridgethillyer
@yokolet 
@cndreisbach 
@seancorfield 
... and I think it would be appropriate to add other people if needed.

I'll change it.

**Comment by bridgethillyer** [comment]
Fixed the typo.

**Comment by k4y3ff** [comment]
Thanks!
